fix(LINGUIST-356): Cover edge case where user has no/insufficient active lists/words in …
LinguistAI/backend pull request #69
Opened 2024-04-28 13:03 UTC by tolgaozgun

…WordSelectionService.java

2024-04-28 17:02 UTC, can-aslan reviewed
LGTM, just left some comments, can you check them and ping me again to review?

2024-04-28 17:02 UTC, can-aslan commented on src/main/java/app/linguistai/bmvp/service/wordbank/WordSelectionService.java
> +                throw new SomethingWentWrongException("Error in selecting new words, you need to add more unknown words to your word bank");
Just `You need to add more unknown words to your word bank` could be more user friendly if we are displaying this to the user. You can mark as resolved directly if not.

2024-04-28 17:02 UTC, can-aslan commented on src/main/java/app/linguistai/bmvp/service/wordbank/WordSelectionService.java
> +            QPredefinedWordList predefinedWordList = readPredefinedWordListFromYamlFile(DEFAULT_WORD_LIST_FILE);
I'm just curious, is reading from the .yaml file each time more performant, or would it be better to store these predefined words in a new DB table and fetch from there?

2024-05-02 21:56 UTC, KardelenCeren requested changes

2024-05-02 21:56 UTC, KardelenCeren commented on src/main/java/app/linguistai/bmvp/service/wordbank/WordSelectionService.java
> +
what does this call do? I think we have already added default words to the selectedWords list at this point

2024-05-07 23:05 UTC, KardelenCeren commented on src/main/java/app/linguistai/bmvp/service/wordbank/WordSelectionService.java
> +
@tolgaozgun

2024-05-11 09:28 UTC, KardelenCeren approved these changes
Looks great!

2024-05-11 09:52 UTC, can-aslan approved these changes

2024-05-11 10:53 UTC, merged